### ISSUE TITLE
About the relationship between custom attributes and UANodeSet Schema objects

### ISSUE THREAD

**Issue by coolbeevip** [kevinherron/uanodeset-parser#7]
I noticed that some objects are defined under the package `com.digitalpetri.opcua.nodeset.attributes` to wrap the UANodeSet.xsd object

But I did not find a one-to-one mapping relationship

I guess class `ObjectNodeAttributes`  is the wrapping class `UAObject`, But it is missing the `ParentNodeId` attribute. 

The class Node in UANodeSet.xsd defines the following inheritance relationship

UANode-> UAInstance -> UAObject
UANode-> UAInstance -> UAVariable

This is a great project, but I am a little confused. Will this part continue to improve?

**Comment by kevinherron** [comment]
These aren't wrappers for the objects in the UANodeSet, they are just "data" classes holding the parsed attributes for Nodes of each NodeClass.

They can be used, along with the parsed reference collections, to build an AddressSpace with all the Nodes defined in a UANodeSet file. 

It might be a little unclear how to use this library right now because I haven't finished building and open sourcing anything that uses it yet, but here's an example (may or may not be its final form): https://gist.github.com/kevinherron/b4268328c3daeec74343ee82b872aef0
 
And here's how I'm using `ModeledAddressSpace` to load the nodes and types from code generated from the UANodeSet defined by the BACnet OPC UA companion spec: https://gist.github.com/kevinherron/3215a4c624f35fdec0d75faaa442f1b3

You'll have to use your imagination a bit when looking at `BacnetNamespace`. None of this code generation or information model is open source right now.

**Comment by coolbeevip** [comment]
Thank you for your reply
